tasks:
  - name: Local terminal
    init: git config --global gpg.format ssh && git config --global user.signingkey "$GITPOD_SIGN_AUTH_KEY_GITHUB" && git config commit.gpgsign true --global
    command: bash
